import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {
      colors: {
        primary: {
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
        },
        neutral: {
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
        },
        dark: {
          bg: 'var(--dark-bg)',
          'bg-hover': 'var(--dark-bg-hover)',
          'bg-active': 'var(--dark-bg-active)',
          border: 'var(--dark-border)',
          text: 'var(--dark-text)',
          'text-muted': 'var(--dark-text-muted)',
          'text-dimmed': 'var(--dark-text-dimmed)',
        },
        light: {
          bg: 'var(--light-bg)',
          'bg-page': 'var(--light-bg-page)',
          'bg-hover': 'var(--light-bg-hover)',
          border: 'var(--light-border)',
          'border-strong': 'var(--light-border-strong)',
          text: 'var(--light-text)',
          'text-secondary': 'var(--light-text-secondary)',
          'text-muted': 'var(--light-text-muted)',
        },
        error: {
          DEFAULT: 'var(--color-error)',
          light: 'var(--color-error-light)',
          border: 'var(--color-error-border)',
          text: 'var(--color-error-text)',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
          light: 'var(--color-warning-light)',
          border: 'var(--color-warning-border)',
          text: 'var(--color-warning-text)',
        },
        success: {
          DEFAULT: 'var(--color-success)',
          light: 'var(--color-success-light)',
          border: 'var(--color-success-border)',
          text: 'var(--color-success-text)',
        },
        info: {
          DEFAULT: 'var(--color-info)',
          light: 'var(--color-info-light)',
          border: 'var(--color-info-border)',
          text: 'var(--color-info-text)',
        },
        severity: {
          critical: 'var(--color-severity-critical)',
          'critical-light': 'var(--color-severity-critical-light)',
          'critical-border': 'var(--color-severity-critical-border)',
          'critical-text': 'var(--color-severity-critical-text)',
          high: 'var(--color-severity-high)',
          'high-light': 'var(--color-severity-high-light)',
          'high-border': 'var(--color-severity-high-border)',
          'high-text': 'var(--color-severity-high-text)',
          medium: 'var(--color-severity-medium)',
          'medium-light': 'var(--color-severity-medium-light)',
          'medium-border': 'var(--color-severity-medium-border)',
          'medium-text': 'var(--color-severity-medium-text)',
          low: 'var(--color-severity-low)',
          'low-light': 'var(--color-severity-low-light)',
          'low-border': 'var(--color-severity-low-border)',
          'low-text': 'var(--color-severity-low-text)',
          info: 'var(--color-severity-info)',
          'info-light': 'var(--color-severity-info-light)',
          'info-border': 'var(--color-severity-info-border)',
          'info-text': 'var(--color-severity-info-text)',
        },
        status: {
          active: 'var(--color-status-active)',
          'active-light': 'var(--color-status-active-light)',
          'active-border': 'var(--color-status-active-border)',
          'active-text': 'var(--color-status-active-text)',
          inactive: 'var(--color-status-inactive)',
          'inactive-light': 'var(--color-status-inactive-light)',
          'inactive-border': 'var(--color-status-inactive-border)',
          'inactive-text': 'var(--color-status-inactive-text)',
          pending: 'var(--color-status-pending)',
          'pending-light': 'var(--color-status-pending-light)',
          'pending-border': 'var(--color-status-pending-border)',
          'pending-text': 'var(--color-status-pending-text)',
          failed: 'var(--color-status-failed)',
          'failed-light': 'var(--color-status-failed-light)',
          'failed-border': 'var(--color-status-failed-border)',
          'failed-text': 'var(--color-status-failed-text)',
          running: 'var(--color-status-running)',
          'running-light': 'var(--color-status-running-light)',
          'running-border': 'var(--color-status-running-border)',
          'running-text': 'var(--color-status-running-text)',
        },
        role: {
          admin: 'var(--color-role-admin)',
          'admin-light': 'var(--color-role-admin-light)',
          'admin-text': 'var(--color-role-admin-text)',
          editor: 'var(--color-role-editor)',
          'editor-light': 'var(--color-role-editor-light)',
          'editor-text': 'var(--color-role-editor-text)',
          viewer: 'var(--color-role-viewer)',
          'viewer-light': 'var(--color-role-viewer-light)',
          'viewer-text': 'var(--color-role-viewer-text)',
        },
        plan: {
          free: 'var(--color-plan-free)',
          'free-light': 'var(--color-plan-free-light)',
          'free-text': 'var(--color-plan-free-text)',
          team: 'var(--color-plan-team)',
          'team-light': 'var(--color-plan-team-light)',
          'team-text': 'var(--color-plan-team-text)',
          enterprise: 'var(--color-plan-enterprise)',
          'enterprise-light': 'var(--color-plan-enterprise-light)',
          'enterprise-text': 'var(--color-plan-enterprise-text)',
        },
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      width: {
        sidebar: 'var(--sidebar-width)',
      },
    },
  },
  plugins: [],
} satisfies Config;
