<script lang="ts">
  /**
   * T149: Synthesis candidate approval queue — Enterprise only.
   */
  import { onMount } from 'svelte';
  import { apiClient, type SynthesisCandidate, ApiError } from '$lib/api';
  import { isEnterprise } from '$lib/stores/tenant';
  import { isAdmin } from '$lib/stores/auth';
  import { goto } from '$app/navigation';

  let candidates = $state<SynthesisCandidate[]>([]);
  let total = $state(0);
  let page = $state(1);
  let loading = $state(false);
  let error = $state<string | null>(null);
  let actionError = $state<string | null>(null);
  let processing: Record<string, boolean> = {};

  async function load() {
    if (!$isEnterprise) return;
    loading = true;
    error = null;
    try {
      const result = await apiClient.synthesis.listCandidates({ page, per_page: 20 });
      candidates = result.items;
      total = result.total;
    } catch (e) {
      error = e instanceof ApiError ? e.message : 'Failed to load candidates';
    } finally {
      loading = false;
    }
  }

  async function handleApprove(candidate: SynthesisCandidate) {
    processing[candidate.id] = true;
    actionError = null;
    try {
      await apiClient.synthesis.approve(candidate.id);
      await load();
    } catch (e) {
      actionError = e instanceof ApiError ? e.message : 'Approve failed';
    } finally {
      processing[candidate.id] = false;
    }
  }

  async function handleReject(candidate: SynthesisCandidate) {
    processing[candidate.id] = true;
    actionError = null;
    try {
      await apiClient.synthesis.reject(candidate.id);
      await load();
    } catch (e) {
      actionError = e instanceof ApiError ? e.message : 'Reject failed';
    } finally {
      processing[candidate.id] = false;
    }
  }

  function formatDate(iso: string): string {
    return new Date(iso).toLocaleDateString();
  }

  const statusColor: Record<string, string> = {
    pending: 'bg-yellow-100 text-yellow-700',
    approved: 'bg-green-100 text-green-700',
    rejected: 'bg-gray-100 text-gray-500',
    failed: 'bg-red-100 text-red-700',
    archived: 'bg-gray-100 text-gray-400',
  };

  onMount(async () => {
    if (!$isEnterprise) {
      await goto('/settings/billing');
      return;
    }
    await load();
  });
</script>

<div>
  <div class="mb-6 flex items-center justify-between">
    <div>
      <h1 class="text-2xl font-bold text-gray-900">Rule Synthesis Queue</h1>
      <p class="mt-1 text-sm text-gray-500">
        Candidate rules generated by Layer 3 — {total} candidates
      </p>
    </div>
  </div>

  {#if !$isEnterprise}
    <div class="rounded-xl border border-amber-200 bg-amber-50 p-6 text-center">
      <p class="text-sm font-medium text-amber-800">
        Rule synthesis is available on the Enterprise plan.
      </p>
      <a href="/settings/billing" class="mt-2 inline-block text-sm text-amber-700 underline">
        Upgrade to Enterprise
      </a>
    </div>
  {:else}
    {#if actionError}
      <div class="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{actionError}</div>
    {/if}

    {#if error}
      <div class="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>
    {/if}

    {#if loading}
      <div class="flex justify-center py-12">
        <span
          class="h-6 w-6 animate-spin rounded-full border-2 border-indigo-600 border-t-transparent"
        ></span>
      </div>
    {:else if candidates.length === 0}
      <div
        class="rounded-xl border border-dashed border-gray-300 py-12 text-center text-sm text-gray-500"
      >
        No synthesis candidates. Candidates appear when 3+ advisories match the same anti-pattern.
      </div>
    {:else}
      <div class="space-y-4">
        {#each candidates as candidate}
          <div class="rounded-xl border border-gray-200 bg-white p-5">
            <div class="mb-3 flex items-start justify-between">
              <div>
                <p class="font-mono text-xs text-gray-500">{candidate.id}</p>
                <div class="mt-1 flex items-center gap-3">
                  <span
                    class="rounded-full px-2 py-0.5 text-xs font-medium {statusColor[
                      candidate.status
                    ] ?? 'bg-gray-100 text-gray-600'}"
                  >
                    {candidate.status}
                  </span>
                  <span class="text-xs text-gray-500"
                    >{candidate.advisory_count} advisory matches</span
                  >
                  {#if candidate.failure_count > 0}
                    <span class="text-xs text-red-500">{candidate.failure_count} failures</span>
                  {/if}
                </div>
              </div>

              <div class="text-xs text-gray-400">Created {formatDate(candidate.created_at)}</div>
            </div>

            {#if candidate.failure_reason}
              <div class="mb-3 rounded-lg bg-red-50 p-2 text-xs text-red-600">
                {candidate.failure_reason}
              </div>
            {/if}

            {#if candidate.generated_rule_yaml}
              <details class="mb-3">
                <summary class="cursor-pointer text-xs font-medium text-indigo-600 hover:underline">
                  View generated YAML
                </summary>
                <pre
                  class="mt-2 overflow-x-auto rounded-lg bg-gray-900 p-3 text-xs text-gray-100">{candidate.generated_rule_yaml}</pre>
              </details>
            {/if}

            {#if candidate.status === 'pending' && $isAdmin}
              <div class="flex gap-2">
                <button
                  onclick={() => handleApprove(candidate)}
                  disabled={processing[candidate.id]}
                  class="rounded-lg bg-green-600 px-3 py-1.5 text-xs font-semibold text-white hover:bg-green-500 disabled:opacity-60"
                >
                  {processing[candidate.id] ? '…' : '✓ Approve'}
                </button>
                <button
                  onclick={() => handleReject(candidate)}
                  disabled={processing[candidate.id]}
                  class="rounded-lg border border-gray-300 px-3 py-1.5 text-xs font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-60"
                >
                  {processing[candidate.id] ? '…' : '✗ Reject'}
                </button>
              </div>
            {/if}
          </div>
        {/each}
      </div>
    {/if}
  {/if}
</div>
