<script lang="ts">
  /**
   * T149: Synthesis candidate approval queue — Enterprise only.
   */
  import { onMount } from 'svelte';
  import { apiClient, type SynthesisCandidate, ApiError } from '$lib/api';
  import { isEnterprise } from '$lib/stores/tenant';
  import { isAdmin } from '$lib/stores/auth';
  import { goto } from '$app/navigation';
  import { Button, Badge, Card, PageHeader, EmptyState, LoadingSkeleton } from '$components/ui';

  let candidates = $state<SynthesisCandidate[]>([]);
  let total = $state(0);
  let page = $state(1);
  let loading = $state(false);
  let error = $state<string | null>(null);
  let actionError = $state<string | null>(null);
  let processing: Record<string, boolean> = {};

  async function load() {
    if (!$isEnterprise) return;
    loading = true;
    error = null;
    try {
      const result = await apiClient.synthesis.listCandidates({ page, per_page: 20 });
      candidates = result.items;
      total = result.total;
    } catch (e) {
      error = e instanceof ApiError ? e.message : 'Failed to load candidates';
    } finally {
      loading = false;
    }
  }

  async function handleApprove(candidate: SynthesisCandidate) {
    processing[candidate.id] = true;
    actionError = null;
    try {
      await apiClient.synthesis.approve(candidate.id);
      await load();
    } catch (e) {
      actionError = e instanceof ApiError ? e.message : 'Approve failed';
    } finally {
      processing[candidate.id] = false;
    }
  }

  async function handleReject(candidate: SynthesisCandidate) {
    processing[candidate.id] = true;
    actionError = null;
    try {
      await apiClient.synthesis.reject(candidate.id);
      await load();
    } catch (e) {
      actionError = e instanceof ApiError ? e.message : 'Reject failed';
    } finally {
      processing[candidate.id] = false;
    }
  }

  function formatDate(iso: string): string {
    return new Date(iso).toLocaleDateString();
  }

  const statusMap: Record<
    string,
    { status?: 'active' | 'inactive' | 'pending' | 'failed'; severity?: 'low' }
  > = {
    pending: { status: 'pending' },
    approved: { status: 'active' },
    rejected: { status: 'inactive' },
    failed: { status: 'failed' },
    archived: { status: 'inactive' },
  };

  onMount(async () => {
    if (!$isEnterprise) {
      await goto('/settings/billing');
      return;
    }
    await load();
  });
</script>

<div>
  <PageHeader
    title="Rule Synthesis Queue"
    description="Candidate rules generated by Layer 3 — {total} candidates"
  />

  {#if !$isEnterprise}
    <Card class="border-status-pending/30 bg-status-pending-light text-center">
      <p class="text-status-pending-text text-sm font-medium">
        Rule synthesis is available on the Enterprise plan.
      </p>
      <a
        href="/settings/billing"
        class="text-primary-500 mt-2 inline-block text-sm hover:underline"
      >
        Upgrade to Enterprise
      </a>
    </Card>
  {:else}
    {#if actionError}
      <div
        class="bg-error-light border-error-border text-error-text mb-4 rounded-lg border p-3 text-sm"
      >
        {actionError}
      </div>
    {/if}

    {#if error}
      <div
        class="bg-error-light border-error-border text-error-text mb-4 rounded-lg border p-3 text-sm"
      >
        {error}
      </div>
    {/if}

    {#if loading}
      <div class="flex justify-center py-12">
        <LoadingSkeleton variant="card" />
      </div>
    {:else if candidates.length === 0}
      <EmptyState
        title="No synthesis candidates"
        description="Candidates appear when 3+ advisories match the same anti-pattern."
      />
    {:else}
      <div class="space-y-4">
        {#each candidates as candidate}
          <Card>
            <div class="mb-3 flex items-start justify-between">
              <div>
                <p class="text-light-text-muted font-mono text-xs">{candidate.id}</p>
                <div class="mt-1 flex items-center gap-3">
                  <Badge status={statusMap[candidate.status]?.status} label={candidate.status} />
                  <span class="text-light-text-secondary text-xs"
                    >{candidate.advisory_count} advisory matches</span
                  >
                  {#if candidate.failure_count > 0}
                    <span class="text-error-text text-xs">{candidate.failure_count} failures</span>
                  {/if}
                </div>
              </div>

              <div class="text-light-text-muted text-xs">
                Created {formatDate(candidate.created_at)}
              </div>
            </div>

            {#if candidate.failure_reason}
              <div
                class="bg-error-light border-error-border text-error-text mb-3 rounded-lg border p-2 text-xs"
              >
                {candidate.failure_reason}
              </div>
            {/if}

            {#if candidate.generated_rule_yaml}
              <details class="mb-3">
                <summary
                  class="text-primary-500 cursor-pointer text-xs font-medium hover:underline"
                >
                  View generated YAML
                </summary>
                <pre
                  class="mt-2 overflow-x-auto rounded-lg bg-neutral-900 p-3 text-xs text-neutral-100">{candidate.generated_rule_yaml}</pre>
              </details>
            {/if}

            {#if candidate.status === 'pending' && $isAdmin}
              <div class="flex gap-2">
                <Button
                  size="sm"
                  onclick={() => handleApprove(candidate)}
                  disabled={processing[candidate.id]}
                >
                  {processing[candidate.id] ? '...' : 'Approve'}
                </Button>
                <Button
                  variant="secondary"
                  size="sm"
                  onclick={() => handleReject(candidate)}
                  disabled={processing[candidate.id]}
                >
                  {processing[candidate.id] ? '...' : 'Reject'}
                </Button>
              </div>
            {/if}
          </Card>
        {/each}
      </div>
    {/if}
  {/if}
</div>
