"""Advisory formatter — produces structured markdown for GitHub PR comments.

Constitution II: Advisories link back to documented incidents.
Formatted for GitHub PR review comments (inline or general).
"""

from __future__ import annotations

from ..incidents.entity import Incident
from ..incidents.enums import RiskLevel
from ..scanning.entities import Advisory


def format_advisory(advisory: Advisory, incidents: list[Incident]) -> str:
    """Format advisory as markdown for GitHub PR review comments.

    Args:
        advisory: The Advisory entity to format.
        incidents: Related incidents for context.

    Returns:
        Markdown-formatted advisory suitable for GitHub comment.

    Template structure:
    - Header with risk level and confidence
    - Analysis text
    - Related incidents list
    - Footer with link to report false positive
    """
    risk_badge = _risk_level_badge(advisory.risk_level)
    confidence_pct = int(advisory.confidence_score * 100)

    header = "## 🔍 Oute Muscle Security Advisory\n\n"
    metrics = (
        f"**Risk Level**: {risk_badge}  |  "
        f"**Confidence**: {confidence_pct}%  |  "
        f"**Model**: `{advisory.llm_model_used}`\n\n"
    )
    analysis = f"{advisory.analysis_text}\n\n"

    incidents_section = _format_incidents_section(incidents)

    footer = (
        "---\n"
        "*Generated by [Oute Muscle](https://oute.me) — "
        "[Report false positive](https://github.com/oute-dev/oute-muscle/issues/new)*"
    )

    return header + metrics + analysis + incidents_section + footer


def _risk_level_badge(risk_level: RiskLevel) -> str:
    """Return a markdown badge for risk level.

    Args:
        risk_level: The RiskLevel enum value.

    Returns:
        Markdown badge string.
    """
    if risk_level == RiskLevel.HIGH:
        return "🔴 **HIGH**"
    elif risk_level == RiskLevel.MEDIUM:
        return "🟡 **MEDIUM**"
    else:  # RiskLevel.LOW
        return "🟢 **LOW**"


def _format_incidents_section(incidents: list[Incident]) -> str:
    """Format the related incidents section.

    Args:
        incidents: List of related incidents.

    Returns:
        Markdown section with incident links, or empty string if no incidents.
    """
    if not incidents:
        return ""

    section = "### 📚 Similar Incidents\n\n"
    for incident in incidents:
        title = incident.title
        url = incident.source_url or "https://oute.me"
        category = incident.category.value
        section += f"- [{title}]({url}) — `{category}`\n"

    section += "\n"
    return section
