"""Incident domain entity — core business object."""

from __future__ import annotations

import uuid
from datetime import date, datetime
from typing import Optional

from pydantic import BaseModel, Field, field_validator, model_validator

from .enums import IncidentCategory, IncidentSeverity


class Incident(BaseModel):
    """A documented production incident that a detection rule is linked to.

    Constitution II: Every rule must be traceable to a real incident.
    The embedding is generated by the Vertex AI adapter, not here.
    """

    model_config = {"frozen": True}

    id: uuid.UUID = Field(default_factory=uuid.uuid4)
    tenant_id: Optional[uuid.UUID] = None  # NULL = shared/public incident

    # Core content
    title: str = Field(min_length=1, max_length=500)
    date: Optional[date] = None
    source_url: Optional[str] = Field(default=None, max_length=2048)
    organization: Optional[str] = Field(default=None, max_length=255)
    category: IncidentCategory
    subcategory: Optional[str] = Field(default=None, max_length=100)
    failure_mode: Optional[str] = None
    severity: IncidentSeverity
    affected_languages: list[str] = Field(default_factory=list)
    anti_pattern: str = Field(min_length=1)
    code_example: Optional[str] = None
    remediation: str = Field(min_length=1)

    # Rule linkage
    static_rule_possible: bool = False
    semgrep_rule_id: Optional[str] = Field(default=None, max_length=50)

    # Vector embedding — 768 dimensions (text-embedding-005)
    # Not required at construction; populated by embedding adapter before persistence
    embedding: Optional[list[float]] = None

    # Metadata
    tags: list[str] = Field(default_factory=list)
    version: int = Field(default=1, ge=1)
    deleted_at: Optional[datetime] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    created_by: uuid.UUID

    @field_validator("embedding")
    @classmethod
    def validate_embedding_dimensions(
        cls, v: Optional[list[float]]
    ) -> Optional[list[float]]:
        if v is not None and len(v) != 768:
            raise ValueError(f"Embedding must have 768 dimensions, got {len(v)}")
        return v

    @field_validator("semgrep_rule_id")
    @classmethod
    def validate_rule_id_format(cls, v: Optional[str]) -> Optional[str]:
        if v is not None:
            parts = v.rsplit("-", 1)
            if len(parts) != 2 or not parts[1].isdigit():
                raise ValueError(
                    f"semgrep_rule_id must follow pattern '{{category}}-{{NNN}}', got '{v}'"
                )
        return v

    @model_validator(mode="after")
    def validate_deletion_state(self) -> "Incident":
        if self.deleted_at is not None and self.semgrep_rule_id is not None:
            raise ValueError(
                "Cannot soft-delete an incident that has an active semgrep_rule_id. "
                "Disable or unlink the rule first."
            )
        return self

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None

    def with_embedding(self, embedding: list[float]) -> "Incident":
        """Return a new Incident with the embedding set (immutable update)."""
        return self.model_copy(update={"embedding": embedding})
